autopep8: http://raw.github.com/hhatto/zsh_completions/master/_autopep8
bpython: http://raw.github.com/hhatto/zsh_completions/master/_bpython
clonedigger: http://raw.github.com/hhatto/zsh_completions/master/_clonedigger
dot: http://raw.github.com/hhatto/zsh_completions/master/_dot
dstat: http://raw.github.com/hhatto/zsh_completions/master/_dstat
fluentd: http://raw.github.com/hhatto/zsh_completions/master/_fluentd
grin: http://raw.github.com/hhatto/zsh_completions/master/_grin
grind: http://raw.github.com/hhatto/zsh_completions/master/_grind
groonga: http://raw.github.com/hhatto/zsh_completions/master/_groonga
groonga-query-log-analyzer: http://raw.github.com/hhatto/zsh_completions/master/_groonga-query-log-analyzer
groonga-suggest-httpd: http://raw.github.com/hhatto/zsh_completions/master/_groonga-suggest-httpd
groonga-suggest-learner: http://raw.github.com/hhatto/zsh_completions/master/_groonga-suggest-learner
gtags: http://raw.github.com/hhatto/zsh_completions/master/_gtags
gunicorn: http://raw.github.com/hhatto/zsh_completions/master/_gunicorn
markdown2: http://raw.github.com/hhatto/zsh_completions/master/_markdown2
mkvirtualenv: http://raw.github.com/hhatto/zsh_completions/master/_mkvirtualenv
nosetests: http://raw.github.com/hhatto/zsh_completions/master/_nosetests
pep8: http://raw.github.com/hhatto/zsh_completions/master/_pep8
pydoc: http://raw.github.com/hhatto/zsh_completions/master/_pydoc
pylint: http://raw.github.com/hhatto/zsh_completions/master/_pylint
pyprof2html: http://raw.github.com/hhatto/zsh_completions/master/_pyprof2html
pyres_manager: http://raw.github.com/hhatto/zsh_completions/master/_pyres_manager
pyres_scheduler: http://raw.github.com/hhatto/zsh_completions/master/_pyres_scheduler
pyres_web: http://raw.github.com/hhatto/zsh_completions/master/_pyres_web
pyres_worker: http://raw.github.com/hhatto/zsh_completions/master/_pyres_worker
setup.py: http://raw.github.com/hhatto/zsh_completions/master/_setup.py
supervisorctl: http://raw.github.com/hhatto/zsh_completions/master/_supervisorctl
supervisord: http://raw.github.com/hhatto/zsh_completions/master/_supervisord
ack: https://raw.github.com/zsh-users/zsh-completions/master/_ack
adb: https://raw.github.com/zsh-users/zsh-completions/master/_adb
android: https://raw.github.com/zsh-users/zsh-completions/master/_android
attach: https://raw.github.com/zsh-users/zsh-completions/master/_attach
baselayout: https://raw.github.com/zsh-users/zsh-completions/master/_baselayout
bpython: https://raw.github.com/zsh-users/zsh-completions/master/_bpython
brew: https://raw.github.com/zsh-users/zsh-completions/master/_brew
bundle: https://raw.github.com/zsh-users/zsh-completions/master/_bundle
cap: https://raw.github.com/zsh-users/zsh-completions/master/_cap
coffee: https://raw.github.com/zsh-users/zsh-completions/master/_coffee
cpanm: https://raw.github.com/zsh-users/zsh-completions/master/_cpanm
debuild: https://raw.github.com/zsh-users/zsh-completions/master/_debuild
dhcpcd: https://raw.github.com/zsh-users/zsh-completions/master/_dhcpcd
ditz: https://raw.github.com/zsh-users/zsh-completions/master/_ditz
emulator: https://raw.github.com/zsh-users/zsh-completions/master/_emulator
eselect: https://raw.github.com/zsh-users/zsh-completions/master/_eselect
fab: https://raw.github.com/zsh-users/zsh-completions/master/_fab
gas: https://raw.github.com/zsh-users/zsh-completions/master/_gas
gcc-config: https://raw.github.com/zsh-users/zsh-completions/master/_gcc-config
geany: https://raw.github.com/zsh-users/zsh-completions/master/_geany
gem: https://raw.github.com/zsh-users/zsh-completions/master/_gem
genlop: https://raw.github.com/zsh-users/zsh-completions/master/_genlop
gentoo_packages: https://raw.github.com/zsh-users/zsh-completions/master/_gentoo_packages
gentoolkit: https://raw.github.com/zsh-users/zsh-completions/master/_gentoolkit
git-flow: https://raw.github.com/zsh-users/zsh-completions/master/_git-flow
git-pulls: https://raw.github.com/zsh-users/zsh-completions/master/_git-pulls
git-wtf: https://raw.github.com/zsh-users/zsh-completions/master/_git-wtf
github: https://raw.github.com/zsh-users/zsh-completions/master/_github
gradle: https://raw.github.com/zsh-users/zsh-completions/master/_gradle
heroku: https://raw.github.com/zsh-users/zsh-completions/master/_heroku
jmeter: https://raw.github.com/zsh-users/zsh-completions/master/_jmeter
jmeter-plugins: https://raw.github.com/zsh-users/zsh-completions/master/_jmeter-plugins
jonas: https://raw.github.com/zsh-users/zsh-completions/master/_jonas
knife: https://raw.github.com/zsh-users/zsh-completions/master/_knife
language_codes: https://raw.github.com/zsh-users/zsh-completions/master/_language_codes
layman: https://raw.github.com/zsh-users/zsh-completions/master/_layman
lein: https://raw.github.com/zsh-users/zsh-completions/master/_lein
lunar: https://raw.github.com/zsh-users/zsh-completions/master/_lunar
lunchy: https://raw.github.com/zsh-users/zsh-completions/master/_lunchy
manage.py: https://raw.github.com/zsh-users/zsh-completions/master/_manage.py
mvn: https://raw.github.com/zsh-users/zsh-completions/master/_mvn
node: https://raw.github.com/zsh-users/zsh-completions/master/_node
optirun: https://raw.github.com/zsh-users/zsh-completions/master/_optirun
pear: https://raw.github.com/zsh-users/zsh-completions/master/_pear
periscope: https://raw.github.com/zsh-users/zsh-completions/master/_periscope
pgsql_utils: https://raw.github.com/zsh-users/zsh-completions/master/_pgsql_utils
pip: https://raw.github.com/zsh-users/zsh-completions/master/_pip
pkcon: https://raw.github.com/zsh-users/zsh-completions/master/_pkcon
play: https://raw.github.com/zsh-users/zsh-completions/master/_play
port: https://raw.github.com/zsh-users/zsh-completions/master/_port
portage: https://raw.github.com/zsh-users/zsh-completions/master/_portage
portage_utils: https://raw.github.com/zsh-users/zsh-completions/master/_portage_utils
redis-cli: https://raw.github.com/zsh-users/zsh-completions/master/_redis-cli
rvm: https://raw.github.com/zsh-users/zsh-completions/master/_rvm
sbt: https://raw.github.com/zsh-users/zsh-completions/master/_sbt
scala: https://raw.github.com/zsh-users/zsh-completions/master/_scala
setup.py: https://raw.github.com/zsh-users/zsh-completions/master/_setup.py
showoff: https://raw.github.com/zsh-users/zsh-completions/master/_showoff
smartmontools: https://raw.github.com/zsh-users/zsh-completions/master/_smartmontools
srm: https://raw.github.com/zsh-users/zsh-completions/master/_srm
ssh-copy-id: https://raw.github.com/zsh-users/zsh-completions/master/_ssh-copy-id
subliminal: https://raw.github.com/zsh-users/zsh-completions/master/_subliminal
symfony: https://raw.github.com/zsh-users/zsh-completions/master/_symfony
task: https://raw.github.com/zsh-users/zsh-completions/master/_task
teamocil: https://raw.github.com/zsh-users/zsh-completions/master/_teamocil
thor: https://raw.github.com/zsh-users/zsh-completions/master/_thor
vagrant: https://raw.github.com/zsh-users/zsh-completions/master/_vagrant
virtualbox: https://raw.github.com/zsh-users/zsh-completions/master/_virtualbox
vpnc: https://raw.github.com/zsh-users/zsh-completions/master/_vpnc
yaourt: https://raw.github.com/zsh-users/zsh-completions/master/_yaourt
zargs: https://raw.github.com/zsh-users/zsh-completions/master/_zargs
