autopep8: https://raw.github.com/hhatto/zsh_completions/master/_autopep8
bpython: https://raw.github.com/hhatto/zsh_completions/master/_bpython
clonedigger: https://raw.github.com/hhatto/zsh_completions/master/_clonedigger
dot: https://raw.github.com/hhatto/zsh_completions/master/_dot
dstat: https://raw.github.com/hhatto/zsh_completions/master/_dstat
fluentd: https://raw.github.com/hhatto/zsh_completions/master/_fluentd
grin: https://raw.github.com/hhatto/zsh_completions/master/_grin
grind: https://raw.github.com/hhatto/zsh_completions/master/_grind
groonga: https://raw.github.com/hhatto/zsh_completions/master/_groonga
groonga-query-log-analyzer: https://raw.github.com/hhatto/zsh_completions/master/_groonga-query-log-analyzer
groonga-suggest-httpsd: https://raw.github.com/hhatto/zsh_completions/master/_groonga-suggest-httpsd
groonga-suggest-learner: https://raw.github.com/hhatto/zsh_completions/master/_groonga-suggest-learner
gtags: https://raw.github.com/hhatto/zsh_completions/master/_gtags
gunicorn: https://raw.github.com/hhatto/zsh_completions/master/_gunicorn
markdown2: https://raw.github.com/hhatto/zsh_completions/master/_markdown2
mkvirtualenv: https://raw.github.com/hhatto/zsh_completions/master/_mkvirtualenv
nosetests: https://raw.github.com/hhatto/zsh_completions/master/_nosetests
pep8: https://raw.github.com/hhatto/zsh_completions/master/_pep8
pydoc: https://raw.github.com/hhatto/zsh_completions/master/_pydoc
pylint: https://raw.github.com/hhatto/zsh_completions/master/_pylint
pyprof2html: https://raw.github.com/hhatto/zsh_completions/master/_pyprof2html
pyres_manager: https://raw.github.com/hhatto/zsh_completions/master/_pyres_manager
pyres_scheduler: https://raw.github.com/hhatto/zsh_completions/master/_pyres_scheduler
pyres_web: https://raw.github.com/hhatto/zsh_completions/master/_pyres_web
pyres_worker: https://raw.github.com/hhatto/zsh_completions/master/_pyres_worker
setup.py: https://raw.github.com/hhatto/zsh_completions/master/src/_setup.py
supervisorctl: https://raw.github.com/hhatto/zsh_completions/master/_supervisorctl
supervisord: https://raw.github.com/hhatto/zsh_completions/master/_supervisord
ack: https://raw.github.com/zsh-users/zsh-completions/master/src/_ack
adb: https://raw.github.com/zsh-users/zsh-completions/master/src/_adb
android: https://raw.github.com/zsh-users/zsh-completions/master/src/_android
attach: https://raw.github.com/zsh-users/zsh-completions/master/src/_attach
baselayout: https://raw.github.com/zsh-users/zsh-completions/master/src/_baselayout
bpython: https://raw.github.com/zsh-users/zsh-completions/master/src/_bpython
brew: https://raw.github.com/zsh-users/zsh-completions/master/src/_brew
bundle: https://raw.github.com/zsh-users/zsh-completions/master/src/_bundle
cap: https://raw.github.com/zsh-users/zsh-completions/master/src/_cap
coffee: https://raw.github.com/zsh-users/zsh-completions/master/src/_coffee
cpanm: https://raw.github.com/zsh-users/zsh-completions/master/src/_cpanm
debuild: https://raw.github.com/zsh-users/zsh-completions/master/src/_debuild
dhcpcd: https://raw.github.com/zsh-users/zsh-completions/master/src/_dhcpcd
ditz: https://raw.github.com/zsh-users/zsh-completions/master/src/_ditz
emulator: https://raw.github.com/zsh-users/zsh-completions/master/src/_emulator
eselect: https://raw.github.com/zsh-users/zsh-completions/master/src/_eselect
fab: https://raw.github.com/zsh-users/zsh-completions/master/src/_fab
gas: https://raw.github.com/zsh-users/zsh-completions/master/src/_gas
gcc-config: https://raw.github.com/zsh-users/zsh-completions/master/src/_gcc-config
geany: https://raw.github.com/zsh-users/zsh-completions/master/src/_geany
gem: https://raw.github.com/zsh-users/zsh-completions/master/src/_gem
genlop: https://raw.github.com/zsh-users/zsh-completions/master/src/_genlop
gentoo_packages: https://raw.github.com/zsh-users/zsh-completions/master/src/_gentoo_packages
gentoolkit: https://raw.github.com/zsh-users/zsh-completions/master/src/_gentoolkit
git-flow: https://raw.github.com/zsh-users/zsh-completions/master/src/_git-flow
git-pulls: https://raw.github.com/zsh-users/zsh-completions/master/src/_git-pulls
git-wtf: https://raw.github.com/zsh-users/zsh-completions/master/src/_git-wtf
github: https://raw.github.com/zsh-users/zsh-completions/master/src/_github
gradle: https://raw.github.com/zsh-users/zsh-completions/master/src/_gradle
heroku: https://raw.github.com/zsh-users/zsh-completions/master/src/_heroku
jmeter: https://raw.github.com/zsh-users/zsh-completions/master/src/_jmeter
jmeter-plugins: https://raw.github.com/zsh-users/zsh-completions/master/src/_jmeter-plugins
jonas: https://raw.github.com/zsh-users/zsh-completions/master/src/_jonas
knife: https://raw.github.com/zsh-users/zsh-completions/master/src/_knife
language_codes: https://raw.github.com/zsh-users/zsh-completions/master/src/_language_codes
layman: https://raw.github.com/zsh-users/zsh-completions/master/src/_layman
lein: https://raw.github.com/zsh-users/zsh-completions/master/src/_lein
lunar: https://raw.github.com/zsh-users/zsh-completions/master/src/_lunar
lunchy: https://raw.github.com/zsh-users/zsh-completions/master/src/_lunchy
manage.py: https://raw.github.com/zsh-users/zsh-completions/master/src/_manage.py
mvn: https://raw.github.com/zsh-users/zsh-completions/master/src/_mvn
node: https://raw.github.com/zsh-users/zsh-completions/master/src/_node
optirun: https://raw.github.com/zsh-users/zsh-completions/master/src/_optirun
pear: https://raw.github.com/zsh-users/zsh-completions/master/src/_pear
periscope: https://raw.github.com/zsh-users/zsh-completions/master/src/_periscope
pgsql_utils: https://raw.github.com/zsh-users/zsh-completions/master/src/_pgsql_utils
pip: https://raw.github.com/zsh-users/zsh-completions/master/src/_pip
pkcon: https://raw.github.com/zsh-users/zsh-completions/master/src/_pkcon
play: https://raw.github.com/zsh-users/zsh-completions/master/src/_play
port: https://raw.github.com/zsh-users/zsh-completions/master/src/_port
portage: https://raw.github.com/zsh-users/zsh-completions/master/src/_portage
portage_utils: https://raw.github.com/zsh-users/zsh-completions/master/src/_portage_utils
redis-cli: https://raw.github.com/zsh-users/zsh-completions/master/src/_redis-cli
rvm: https://raw.github.com/zsh-users/zsh-completions/master/src/_rvm
sbt: https://raw.github.com/zsh-users/zsh-completions/master/src/_sbt
scala: https://raw.github.com/zsh-users/zsh-completions/master/src/_scala
setup.py: https://raw.github.com/zsh-users/zsh-completions/master/src/_setup.py
showoff: https://raw.github.com/zsh-users/zsh-completions/master/src/_showoff
smartmontools: https://raw.github.com/zsh-users/zsh-completions/master/src/_smartmontools
srm: https://raw.github.com/zsh-users/zsh-completions/master/src/_srm
ssh-copy-id: https://raw.github.com/zsh-users/zsh-completions/master/src/_ssh-copy-id
subliminal: https://raw.github.com/zsh-users/zsh-completions/master/src/_subliminal
symfony: https://raw.github.com/zsh-users/zsh-completions/master/src/_symfony
task: https://raw.github.com/zsh-users/zsh-completions/master/src/_task
teamocil: https://raw.github.com/zsh-users/zsh-completions/master/src/_teamocil
thor: https://raw.github.com/zsh-users/zsh-completions/master/src/_thor
vagrant: https://raw.github.com/zsh-users/zsh-completions/master/src/_vagrant
virtualbox: https://raw.github.com/zsh-users/zsh-completions/master/src/_virtualbox
vpnc: https://raw.github.com/zsh-users/zsh-completions/master/src/_vpnc
yaourt: https://raw.github.com/zsh-users/zsh-completions/master/src/_yaourt
zargs: https://raw.github.com/zsh-users/zsh-completions/master/src/_zargs
