#!/usr/bin/env python
import os
import sys
import argparse
from StringIO import StringIO
import requests
import yaml

PKGLIST_URL = "https://raw.github.com/hhatto/zci/master/package.yaml"
DEFAULTS = {'install_path': '~/.zsh/completion/'}


def load_package():
    f = requests.get(PKGLIST_URL)
    packages = yaml.load(StringIO(f.text))
    return packages


def get_zshcomp(name, url):
    f = requests.get(url)
    return f.text


def find_zshcomppath():
    pass


def install_zshcomp(name, zshfunc):
    _name = '_' + name
    path = os.path.join(os.path.expanduser(DEFAULTS['install_path']), _name)
    zshfile = open(path, 'w+')
    zshfile.write(zshfunc)
    zshfile.close()


def get_optionparser():
    parser = argparse.ArgumentParser(prog='zci')
    sub_commands = parser.add_subparsers(help='zci sub command help')
    install = sub_commands.add_parser('install', help='install package')
    install.add_argument('target_package', help='package name')
    sub_commands.add_parser('help', help='sub command help')
    return parser


def main():
    parser = get_optionparser()
    opts = parser.parse_args(sys.argv[1:])
    target_package = opts.target_package
    pkg = load_package()
    url = pkg.get(target_package)
    if not url:
        print "%s not found" % target_package
        return -1
    zshfunc = get_zshcomp(target_package, url)
    install_zshcomp(target_package, zshfunc)
    print "'%s' zsh completion function install success." % target_package
    return 0

if __name__ == '__main__':
    sys.exit(main())
